### ISSUE TITLE
Python 2.7 TypeError: unicode argument expected, got 'str'

### ISSUE THREAD

**Issue by ishiland** [ishiland/python-geosupport#10]
While running [appveyor CI tests](https://ci.appveyor.com/project/ishiland/python-geosupport), this error occurs on all builds with python 2.7:

```
ERROR: test_print (tests.unit.test_help.TestHelp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\python-geosupport\tests\unit\test_help.py", line 32, in test_print
    o = self.geosupport.help()
  File "c:\projects\python-geosupport\geosupport\geosupport.py", line 146, in help
    print(return_val)
TypeError: unicode argument expected, got 'str'
----------------------------------------------------------------------
```

**Comment by ishiland** [comment]
b6b895c
