### ISSUE TITLE
Trying to get the Linux version of Geosupport running w/ this library on CentOS8

### ISSUE THREAD

**Issue by nygeog** [ishiland/python-geosupport#24]
Hi, thank you for this library, I've set this up in Windows but trying to get the Linux version of Geosupport running w/ this library on CentOS8.

I ran the following:
```
from geosupport import Geosupport
g = Geosupport()

# Call the address processing function by name
result = g.address(house_number=125, street_name='Worth St', borough_code='Mn')
```

I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/geosupport/geosupport.py", line 63, in __init__
    self.geolib = cdll.LoadLibrary("libgeo.so")
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 421, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgeo.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/geosupport/geosupport.py", line 75, in __init__
    e, self.py_bit, self.py_bit
geosupport.error.GeosupportError: libgeo.so: cannot open shared object file: No such file or directory
You are currently using a 64-bit Python interpreter. Is the installed version of Geosupport 64-bit?
```

Should I use a 32-bit Python interpreter? If so, is there a set of directions you'd recommend?

**Comment by nygeog** [comment]
Actually, I'll close this, I have it running after moving the folder to my home. And following the directions in `doc/linux_geosupport_doc.txt`:

```
LD_LIBRARY_PATH=$HOME/version-20d_20.4/lib
export LD_LIBRARY_PATH
GEOFILES=$HOME/version-20d_20.4/fls/
export GEOFILES 
```

I may have done something wrong setting these env. variables initially.
