### ISSUE TITLE
Having initialization issue

### ISSUE THREAD

**Issue by kagnas** [ishiland/python-geosupport#35]
Hello, 

I have both Python 3.12 (64 bit) and Geosupport version 23d (64 bit) for Window on my computer. I have the FLs directory at C:\Program Files\Geosupport Desktop Edition\fls but I am getting the following error.

**Original Code:**
```
directory = r'C:\Program Files\Geosupport Desktop Edition\Fls'
from geosupport import Geosupport
g = Geosupport()
result = g.address(house_number=125, street_name='Worth St', borough_code='Mn')
```
**Error**
```
Traceback (most recent call last):
  File "C:\Users\kagnas\PycharmProjects\Geocoding\Geocoding Lesson 1\check.py", line 5, in <module>
    result = g.address(house_number=125, street_name='Worth St', borough_code='Mn')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kagnas\PycharmProjects\Geocoding\Geocoding Lesson 1\venv\Lib\site-packages\geosupport\geosupport.py", line 117, in call
    raise GeosupportError(
geosupport.error.GeosupportError: ERROR ACCESSING GEOSUPPORT FILE: GRID1. NOTIFY SYSTEM SUPPORT ERROR ACCESSING GEOSUPPORT FILE: PAD. NOTIFY SYSTEM SUPPORT
```

I checked if the directory exists as well as  `GRID1` and `PAD`. Then, checked if it will initialize to the Geosupport library but I see that those two files are present in the directory, but the error persists attempting to initialize Geosupport. I was wondering if you please assist with this, thank you!

**Comment by ishiland** [comment]
which version of python-geosupport are you using?

**Comment by ishiland** [comment]
closing since im unable to recreate the issue
